// <auto-generated />
namespace CloudKids.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialmig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialmig));
        
        string IMigrationMetadata.Id
        {
            get { return "202003181821558_initial-mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
